# Welcome to Jekyll!
title: Online Resume
url:
baseurl:

# Sass setting
sass:
  sass_dir: _sass
  style:    compressed

# Custom
lang: en
open: true                  # show or hide your resume
allow_search_engines: true  # allow your resume indexing by search engine, 'true' or 'false'
analytics:
  google:                   # google analytics
  cloudflare:               # cloudflare analytics
  umami:
    script: https://u.tarrex.com/u.js                # umami analytics script src (Replace it with your own config)
    website_id: af636e2d-31ae-46f1-9071-82b1745143a9 # umami analytics website id (Replace it with your own config)
    domains: tarrex.github.io,tarrex.com             # umami analytics domains (Replace it with your own config)
description:
open_graph:
  enable: true                        # enable open graph meta tags
  image: /assets/images/profile.png   # open graph image path

# Style
text_direction: ltr
date_format: "%Y-%m-%d"
theme_color: "#1DA1F2"
contact_delimiter: "·"
section_icon: true
section_title: uppercase
section_align: start
section_line: dashed
section_background: false
skill_level_icon: lightbulb
link_icon: true
site_footer: true

